#!/bin/bash

echo "🚀 Resume & JD Matcher Deployment Guide 🚀"
echo "📋 Step-by-Step Deployment Instructions:"
echo ""
echo "1️⃣ BACKEND DEPLOYMENT (Render):"
echo "   • Go to https://render.com and sign up"
echo "   • Click 'New +' → 'Web Service'"
echo "   • Connect your GitHub repository"
echo "   • Configure:"
echo "     - Name: resume-jd-matcher-backend"
echo "     - Environment: Python 3"
echo "     - Build Command: pip install -r requirements.txt"
echo "     - Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo "   • Deploy and copy the URL (e.g., https://your-app.onrender.com)"
echo ""
echo "2️⃣ FRONTEND DEPLOYMENT (Vercel):"
echo "   • Go to https://vercel.com and sign up"
echo "   • Click 'New Project'"
echo "   • Import your GitHub repository"
echo "   • Add environment variable:"
echo "     - NEXT_PUBLIC_API_URL: [Your Render backend URL]"
echo "   • Deploy!"
echo ""
echo "3️⃣ TEST YOUR DEPLOYED APP:"
echo "   • Frontend: https://your-app.vercel.app"
echo "   • Backend: https://your-backend.onrender.com"
echo ""
echo "🎯 Your app will be accessible to everyone worldwide!"
echo ""
echo "💡 Pro Tips:"
echo "   • Test thoroughly before sharing"
echo "   • Monitor Render usage (free tier limits)"
echo "   • Consider upgrading for production use"
echo ""
echo "📚 Full deployment guide available in DEPLOYMENT.md"
